version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - /Users/xhnsylk/code/automatic_scheduler/data:/var/lib/postgresql/data
    
  backend:
    tty: true
    build:
      context: ./auto_scheduler
      dockerfile: Dockerfile
    # command: /code/wait-for-it.sh db:5432
    environment:
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1] 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - /Users/xhnsylk/code/automatic_scheduler/auto_scheduler:/code
    depends_on:
      - db
  
  frontend:
    build:
      context: ./auto_scheduler/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /Users/xhnsylk/code/automatic_scheduler/auto_scheduler/frontend:/app
  
